### PR TITLE
Added config files

### PR DESCRIPTION
**Pull request by kemeirnld2**

### CODE REVIEW

**Comment by maxwelbarno** [comment]
Which `config files` did you add sir? can't see any configuration files changed or added

**Comment by maxwelbarno** [comment]
Nonetheless, the code is clean. Proceed!

**Review by maxwelbarno — APPROVED** [review]

**Comment by kemeirnld2** [comment]
> Which `config files` did you add sir? can't see any configuration files changed or added

The git ignore excluded the instance and config,py file

**Comment by kemeirnld2** [comment]
> > Which `config files` did you add sir? can't see any configuration files changed or added
> 
> The git ignore excluded the instance and config,py file

image

**Comment by maxwelbarno** [comment]
> > > Which `config files` did you add sir? can't see any configuration files changed or added
> > 
> > 
> > The git ignore excluded the instance and config,py file
> 
> image
Ok. Didn't see incoming changes afterall. But please merge abd proceed!

**Pull request merged**
